### PR TITLE
Player

### PR DESCRIPTION
**Pull request by achhansrun**
Added basic player

### CODE REVIEW

**Comment by Akantonio** [comment]
Add some input mapping pls. I need it

**Comment by femikol** [comment]
No input mapping lmao

**Review by Akantonio — COMMENTED** [review]
no player input changes

**Review by femikol — CHANGES_REQUESTED** [review]
Test request change

**Review by Akantonio — CHANGES_REQUESTED** [review]
Add player Input in project setting

**Comment by achhansrun** [comment]
We already had input mapping, however, it was the default settings that would be harder to customize.

**Review by Akantonio — APPROVED** [review]
Saw no major issues.

**Pull request merged**
